Repository likelion12th-hufs-global-team5/team5-FE, pull requests merged in 2024-05, with the labels that each got.

#7 브랜치 전환 전 커밋
  mini-project/package-lock.json
  mini-project/package.json
  mini-project/public/robots.txt
  mini-project/src/App.jsx
  mini-project/src/Wrapper.jsx
  mini-project/src/features/counter/Counter.js
  mini-project/src/features/counter/Counter.module.css
  mini-project/src/features/counter/counterAPI.js
  mini-project/src/features/counter/counterSlice.js
  mini-project/src/features/counter/counterSlice.spec.js
  mini-project/src/pages/Curriculum.jsx
  mini-project/src/pages/Login.jsx
  mini-project/src/pages/Main.jsx
  mini-project/src/pages/Profile.jsx
  mini-project/src/pages/Project.jsx
  mini-project/src/pages/Signin.jsx
Labels: ⚙ Setting, ✅ Test

#10 setting:초기 설정 globalCss 제외 끝
  miniproject/.gitignore
  miniproject/README.md
  miniproject/package-lock.json
  miniproject/package.json
  miniproject/public/%PUBLIC_URL%/logo.png
  miniproject/public/index.html
  miniproject/public/logo.png
  miniproject/public/manifest.json
  miniproject/public/robots.txt
  miniproject/src/App.css
  miniproject/src/App.js
  miniproject/src/index.css
  miniproject/src/index.js
  miniproject/src/logo.svg
  miniproject/src/pages/Curriculum.js
  miniproject/src/pages/JoinMembership.js
  miniproject/src/pages/Login.js
  miniproject/src/pages/Main.js
  miniproject/src/pages/Member.js
  miniproject/src/pages/Profile.js
  miniproject/src/pages/Project.js
  miniproject/src/redux/sessionSlice.js
  miniproject/src/redux/store.js
  miniproject/src/redux/userSlice.js
  miniproject/src/reportWebVitals.js
  miniproject/src/router.js
  miniproject/src/setupTests.js
Labels: ⚙ Setting

#12 setting:Globalcss 설정 중앙 정렬만 남음 / Header component 만들다가 그만둠
  miniproject/package-lock.json
  miniproject/package.json
  miniproject/src/App.js
  miniproject/src/components/Header.js
  miniproject/src/index.js
  miniproject/src/pages/Curriculum.js
  miniproject/src/pages/JoinMembership.js
  miniproject/src/pages/Login.js
  miniproject/src/pages/Main.js
  miniproject/src/pages/Member.js
  miniproject/src/pages/Profile.js
  miniproject/src/pages/Project.js
  miniproject/src/styles/globalCss.js
  miniproject/src/styles/theme.js
Labels: ⚙ Setting

#15 setting:globalcss 계속 만져보는 중 /design:main 작업 진행
  miniproject/src/components/Footer.js
  miniproject/src/components/Header.js
  miniproject/src/pages/Main.js
  miniproject/src/styles/theme.js
Labels: 🎨 Html&Css, ⚙ Setting

#16 design:randomStars가 해결이 안되서 Login ui작업으로 넘어 가기 전 커밋 날림
  miniproject/src/components/Circle.js
  miniproject/src/components/Header.js
  miniproject/src/components/Logo.js
  miniproject/src/components/RandomStars.js
  miniproject/src/pages/Curriculum.js
  miniproject/src/pages/Login.js
  miniproject/src/pages/Main.js
  miniproject/src/pages/Member.js
  miniproject/src/pages/Profile.js
  miniproject/src/pages/Project.js
Labels: 🎨 Html&Css

#19 design:Login ui 작업중 중간 commit
  miniproject/src/pages/Login.js
  miniproject/src/pages/Main.js
  miniproject/src/styles/theme.js
Labels: 🎨 Html&Css

#20 design:Circle component transition animation 설정. 좀 더 부드러운 움직임 설정 필요
  miniproject/src/components/Circle.js
  miniproject/src/components/Logo.js
Labels: 🎨 Html&Css

#21 design: transition 넣어서 자연스럽게 설정함
  miniproject/src/components/Circle.js
  miniproject/src/components/Header.js
Labels: 🎨 Html&Css

#25 design: Session bar 작성, 공통(common) 파트 디자인
  miniproject/src/components/Sessionbar.js
  miniproject/src/pages/Curriculum.js
Labels: 💻 All

#26 프로젝트페이지:9칸구성
  miniproject/src/pages/Project.js
  miniproject/src/pages/ProjectUpload.js
Labels: ⚙ Setting

#27 design:Main.js 미디어쿼리 시도 / JoinMembership.js 틀 완성
  miniproject/src/components/Circle.js
  miniproject/src/components/Footer.js
  miniproject/src/components/Header.js
  miniproject/src/components/Logo.js
  miniproject/src/pages/JoinMembership.js
  miniproject/src/pages/Login.js
  miniproject/src/pages/Main.js
  miniproject/src/styles/theme.js
Labels: 🎨 Html&Css

#30 design:Curriculum 페이지 완성 + Sessionbar 수정
  miniproject/src/components/Sessionbar.js
  miniproject/src/pages/Curriculum.js
Labels: 🎨 Html&Css

#31 design:JoinMembership.js joinMembership Div 수정 완료
  miniproject/src/components/LogoCircle.js
  miniproject/src/pages/JoinMembership.js
  miniproject/src/styles/theme.js
Labels: 🎨 Html&Css

#32 design:LogoCircle.js Login,Join용 component 만들어서 크기와 간격 조정
  miniproject/src/components/Header.js
  miniproject/src/components/LogoCircle.js
  miniproject/src/pages/JoinMembership.js
  miniproject/src/pages/Login.js
Labels: 🎨 Html&Css

#33 feat:JoinMembership Api 관련 redux 파일 수정, 추가 작업
  miniproject/package-lock.json
  miniproject/package.json
  miniproject/src/api/authApi.js
  miniproject/src/pages/JoinMembership.js
  miniproject/src/pages/Login.js
  miniproject/src/redux/authSlice.js
  miniproject/src/redux/store.js
Labels: ✨ Feature, ✅ Test

#35 feat:js-cookie 사용해서 main 쿠키 설정 진행
  miniproject/package.json
  miniproject/src/components/Header.js
  miniproject/src/cookie/CheckLoginStatus.js
  miniproject/src/pages/JoinMembership.js
  miniproject/src/pages/Login.js
  miniproject/src/pages/Main.js
Labels: ✨ Feature

#36 feat:input value FormData에 저장 완료
  miniproject/src/pages/JoinMembership.js
Labels: 📬 API, ✨ Feature

#37 feat:api 코드 작성 후 로그인 버튼 누르면 form제출 후 Main이동
  miniproject/src/pages/Login.js
Labels: 📬 API, ✨ Feature

#38 feat:alert 창 login, join에 추가 / redux:sessionSlice 삭제
  miniproject/src/pages/JoinMembership.js
  miniproject/src/pages/Login.js
  miniproject/src/redux/sessionSlice.js
  miniproject/src/redux/store.js
Labels: 📃Docs, ✨ Feature

#40 feat:redux 코드 다시 작성(userSlice, store, App.js)
  miniproject/src/App.js
  miniproject/src/redux/store.js
  miniproject/src/redux/userSlice.js
Labels: 📬 API, ✨ Feature

#42 design:star 기능 구현 후 main, login, join 페이지에 추가
  miniproject/src/components/Footer.js
  miniproject/src/components/Header.js
  miniproject/src/components/RandomStars.js
  miniproject/src/components/Star.js
  miniproject/src/components/Stars.js
  miniproject/src/pages/JoinMembership.js
  miniproject/src/pages/Login.js
  miniproject/src/pages/Main.js
  miniproject/src/styles/theme.js
Labels: 🎨 Html&Css

#43 feat:Main, Login, Join page에 input value localStorage에 저장하는 코드 완성
  miniproject/src/pages/JoinMembership.js
  miniproject/src/pages/Login.js
  miniproject/src/pages/Main.js
Labels: 📬 API, ✨ Feature

#45 design : Curriculum 관련 페이지(기본, upload, detail) desigin 수정 및 완성
  miniproject/src/pages/Curriculum.js
  miniproject/src/pages/CurriculumDetail.js
  miniproject/src/pages/CurriculumUpload.js
Labels: 🎨 Html&Css

#46 design:header, footer간격 조정
  miniproject/src/pages/Curriculum.js
  miniproject/src/pages/CurriculumDetail.js
  miniproject/src/pages/CurriculumUpload.js
  miniproject/src/pages/Profile.js
  miniproject/src/pages/Project.js
  miniproject/src/pages/ProjectDetail.js
  miniproject/src/pages/ProjectUpload.js
Labels: 🎨 Html&Css

#47 edit:Main.js testInput del / setting:vercel install
  miniproject/src/pages/Main.js
Labels: 📃Docs, ⚙ Setting

#48 setting:vercel 작업을 위해 디렉토리 수정
  .gitignore
  miniproject/README.md
  package-lock.json
  package.json
  public/%PUBLIC_URL%/logo.png
  public/index.html
  public/logo.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/api/authApi.js
  src/components/Circle.js
  src/components/Footer.js
  src/components/Header.js
  src/components/ImageContainers.js
  src/components/Logo.js
  src/components/LogoCircle.js
  src/components/RandomStars.js
  src/components/Sessionbar.js
  src/components/Star.js
  src/components/Stars.js
  src/cookie/CheckLoginStatus.js
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/Curriculum.js
  src/pages/CurriculumDetail.js
  src/pages/CurriculumUpload.js
  src/pages/JoinMembership.js
  src/pages/Login.js
  src/pages/Main.js
  src/pages/Member.js
  src/pages/Profile.js
  src/pages/Project.js
  src/pages/ProjectDetail.js
  src/pages/ProjectUpload.js
  src/redux/authSlice.js
  src/redux/store.js
  src/redux/userSlice.js
  src/reportWebVitals.js
  src/router.js
  src/setupTests.js
  src/styles/globalCss.js
  src/styles/theme.js
Labels: 🌏 Deploy, ⚙ Setting

#49 setting:GoogleFont
  public/index.html
Labels: 📃Docs, ⚙ Setting

#50 design:반응형 수정 중간 커밋
  src/components/Star.js
  src/components/Stars.js
  src/pages/JoinMembership.js
  src/pages/Login.js
  src/styles/theme.js
Labels: 🎨 Html&Css

#51 design:Login, Join Button active edit
  src/pages/JoinMembership.js
  src/pages/Login.js
Labels: 🎨 Html&Css

#53 design:profile.js 중간 / password input component 작업 중
  src/components/Password.js
  src/pages/Profile.js
  src/styles/theme.js
Labels: 🎨 Html&Css

#54 design(Profile): img issue 해결 못함
  src/components/LogoCircle.js
  src/components/Password.js
  src/pages/Member.js
  src/pages/Profile.js
  src/styles/theme.js
Labels: 🎨 Html&Css

#56 design(ProjectUpload/ProjectDetail):Button hover css 추가 / test code 삭제
  src/pages/ProjectDetail.js
  src/pages/ProjectUpload.js
Labels: 🎨 Html&Css

#57 feat(projectUpload) : button 속성 변경
  src/pages/ProjectUpload.js
Labels: 💻 All

#59 api : Curriculum.js 파일 api 작업 1차 완료
  src/pages/Curriculum.js
Labels: 📬 API

#62 변경된 api 예제로 수정
  src/pages/Curriculum.js
Labels: 📬 API

#63 design(Member,Profile) : 위치 조정, profile img button
  src/pages/Member.js
  src/pages/Profile.js
Labels: 🎨 Html&Css

#64 api : Curriculum.js 연결 + 프록시? 설정(package.json 수정)
  package.json
  src/pages/Curriculum.js
  src/pages/CurriculumDetail.js
  src/pages/CurriculumUpload.js
Labels: 📬 API

#66 delete(clone-prj):이중 클론된 플젝 삭제
  miniproject/.gitignore
  miniproject/README.md
  miniproject/package-lock.json
  miniproject/package.json
  miniproject/public/%PUBLIC_URL%/logo.png
  miniproject/public/index.html
  miniproject/public/logo.png
  miniproject/public/manifest.json
  miniproject/public/robots.txt
  miniproject/src/App.css
  miniproject/src/App.js
  miniproject/src/api/authApi.js
  miniproject/src/components/Circle.js
  miniproject/src/components/Footer.js
  miniproject/src/components/Header.js
  miniproject/src/components/Logo.js
  miniproject/src/components/LogoCircle.js
  miniproject/src/components/RandomStars.js
  miniproject/src/components/Sessionbar.js
  miniproject/src/cookie/CheckLoginStatus.js
  miniproject/src/index.css
  miniproject/src/index.js
  miniproject/src/logo.svg
  miniproject/src/pages/Curriculum.js
  miniproject/src/pages/CurriculumDetail.js
  miniproject/src/pages/CurriculumUpload.js
  miniproject/src/pages/JoinMembership.js
  miniproject/src/pages/Login.js
  miniproject/src/pages/Main.js
  miniproject/src/pages/Member.js
  miniproject/src/pages/Profile.js
  miniproject/src/pages/Project.js
  miniproject/src/pages/ProjectDetail.js
  miniproject/src/pages/ProjectUpload.js
  miniproject/src/redux/authSlice.js
  miniproject/src/redux/store.js
  miniproject/src/redux/userSlice.js
  miniproject/src/reportWebVitals.js
  miniproject/src/router.js
  miniproject/src/setupTests.js
  miniproject/src/styles/globalCss.js
  miniproject/src/styles/theme.js
Labels: 📃Docs

#67 design(Logo):시도는 했지만 실적이 없는
  src/components/LogoCircle.js
  src/pages/JoinMembership.js
  src/pages/Login.js
Labels: 🎨 Html&Css, ⚙ Setting, ✅ Test

#68 design : Profile
  src/components/Password.js
  src/pages/Profile.js
Labels: 🎨 Html&Css

#71 feat(api연동):CORS 에러는 login page에서는 해결
  public/image/LogoImg.png
  src/App.js
  src/components/Password.js
  src/cookie/CheckLoginStatus.js
  src/index.js
  src/pages/JoinMembership.js
  src/pages/Login.js
  src/pages/Main.js
  src/pages/Profile.js
  src/redux/store.js
  src/redux/userSlice.js
Labels: 🌏 Deploy, ✨ Feature

#72 fix(profile):api 연동 코드 오류 주석 처리
  src/components/Password.js
  src/pages/Profile.js
Labels: ⚠️ BugFIx, 🌏 Deploy, ✨ Feature

#73 feat(API) : redux-toolkit userSlice.js, Login.js edit
  src/pages/JoinMembership.js
  src/pages/Login.js
  src/redux/authSlice.js
  src/redux/userSlice.js
  src/styles/theme.js
Labels: 📬 API, 🌏 Deploy, ✨ Feature

#77 feat(API):JoinMembership/Login API 연동 완성
  src/components/LogoCircle.js
  src/pages/JoinMembership.js
  src/pages/Login.js
Labels: 📬 API, ✨ Feature

#78 design(JoinMembership):input elems gap setting, buttons hover, active…
  src/components/Password.js
  src/pages/JoinMembership.js
  src/pages/Login.js
  src/pages/Member.js
  src/pages/Profile.js
Labels: 🎨 Html&Css, 🔨 Refactor

#80 error:react 패키지 종속성 error 해결
  package-lock.json
  package.json
  src/.babelrc
  src/redux/projectSlice.js
  src/redux/store.js
Labels: ⚠️ BugFIx

#81 feat(Cookie):설정중 중간 커밋
  src/components/Header.js
  src/pages/Login.js
  src/pages/Main.js
  src/pages/Profile.js
Labels: 📬 API

#82 design(star) : profile, memberpage add
  src/components/Circle.js
  src/components/Stars.js
  src/pages/Login.js
  src/pages/Member.js
  src/pages/Profile.js
  src/pages/Project.js
  src/redux/userSlice.js
Labels: 🎨 Html&Css

#83 design : star 추가
  src/pages/Curriculum.js
  src/pages/CurriculumDetail.js
  src/pages/CurriculumUpload.js
Labels: 🎨 Html&Css

#85 design :Curriculum font
  src/components/Sessionbar.js
  src/pages/Curriculum.js
Labels: 🎨 Html&Css

#86 design-edit:중간 커밋
  src/pages/Profile.js
Labels: 🎨 Html&Css

#89 design(ProjectButton):project 업로드하기 버튼 edit
  package-lock.json
  src/pages/Project.js
Labels: 🎨 Html&Css

#90 design : border
  src/pages/JoinMembership.js
  src/pages/Login.js
  src/pages/Profile.js
Labels: 🎨 Html&Css

#91 design : border
  src/pages/JoinMembership.js
Labels: 🎨 Html&Css
